-- ============================================================
-- Oracle Migration Script (Corrected v2)
-- Target: Oracle 12c+
-- Run this script FIRST, then run agricSociety_advanced_fixed.sql
-- All fixes are marked with -- [FIX] comments
-- ============================================================


-- ------------------------------------------------------------
-- TABLES
-- ------------------------------------------------------------

CREATE TABLE "branch_table" (
    "branchID"   NUMBER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "branchName" VARCHAR2(100) NOT NULL,
    "location"   VARCHAR2(100) NOT NULL,
    CONSTRAINT "pk_branch" PRIMARY KEY ("branchID")
);

CREATE TABLE "category_table" (
    "categoryID"   NUMBER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "categoryName" VARCHAR2(50)  NOT NULL,
    "entryFee"     NUMBER(10,2),
    "annualFee"    NUMBER(10,2),
    CONSTRAINT "pk_category"              PRIMARY KEY ("categoryID"),
    CONSTRAINT "uq_category_categoryName" UNIQUE      ("categoryName"),
    CONSTRAINT "ck_category_annualFee"    CHECK       ("annualFee" >= 0),
    CONSTRAINT "ck_category_entryFee"     CHECK       ("entryFee"  >= 0)
);

CREATE TABLE "member_table" (
    "memberID"   NUMBER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "firstName"  VARCHAR2(30)  NOT NULL,
    "secondName" VARCHAR2(30)  NOT NULL,
    -- [FIX] Added NOT NULL — email is used as login credential; must be present
    "email"      VARCHAR2(100) NOT NULL,
    -- [FIX] Added NOT NULL — phone is a key contact field
    "phoneNo"    VARCHAR2(20)  NOT NULL,
    "branchID"   NUMBER        NOT NULL,
    "categoryID" NUMBER        NOT NULL,
    "joinDate"   DATE          DEFAULT SYSDATE,
    CONSTRAINT "pk_member"         PRIMARY KEY ("memberID"),
    CONSTRAINT "uq_member_phoneNo" UNIQUE      ("phoneNo"),
    CONSTRAINT "uq_member_email"   UNIQUE      ("email")
);

CREATE TABLE "payment_table" (
    "paymentID"   NUMBER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "memberID"    NUMBER        NOT NULL,
    -- [FIX] Added NOT NULL — a payment with NULL amount passes CHECK silently in Oracle
    "amount"      NUMBER(10,2)  NOT NULL,
    "paymentType" VARCHAR2(30)  NOT NULL,
    "paymentDate" DATE          DEFAULT SYSDATE,
    CONSTRAINT "pk_payment"        PRIMARY KEY ("paymentID"),
    CONSTRAINT "ck_payment_amount" CHECK       ("amount" > 0)
);

CREATE TABLE "resource_table" (
    "resourceID"      NUMBER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "title"           VARCHAR2(255) NOT NULL,
    "type"            VARCHAR2(50)  NOT NULL,
    "availableCopies" NUMBER        DEFAULT 0 NOT NULL,
    CONSTRAINT "pk_resource"                 PRIMARY KEY ("resourceID"),
    CONSTRAINT "ck_resource_availableCopies" CHECK       ("availableCopies" >= 0)
);

CREATE TABLE "borrow_table" (
    "borrowID"   NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "memberID"   NUMBER NOT NULL,
    "resourceID" NUMBER NOT NULL,
    "borrowDate" DATE   DEFAULT SYSDATE,
    "returnDate" DATE,
    CONSTRAINT "pk_borrow" PRIMARY KEY ("borrowID")
    -- [FIX] Removed uq_borrow_active unique constraint from here.
    --       Oracle B-tree indexes do NOT index NULLs, so
    --       UNIQUE (memberID, resourceID, returnDate) with returnDate IS NULL
    --       for active borrows does NOT prevent duplicate active borrows.
    --       Replaced below with a function-based unique index that uses a
    --       sentinel date (9999-12-31) in place of NULL so it IS indexed.
);

-- [FIX] Function-based unique index replaces the broken uq_borrow_active constraint.
--       NVL maps NULL returnDate to a sentinel value so active borrows ARE indexed,
--       preventing a member from having two active borrows of the same resource.
CREATE UNIQUE INDEX "uix_borrow_active"
    ON "borrow_table" (
        "memberID",
        "resourceID",
        NVL("returnDate", DATE '9999-12-31')
    );

CREATE TABLE "official_table" (
    "officialID" NUMBER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "fullName"   VARCHAR2(60)  NOT NULL,
    "position"   VARCHAR2(50)  NOT NULL,
    "phoneNo"    VARCHAR2(20)  NOT NULL,
    "branchID"   NUMBER        NOT NULL,
    CONSTRAINT "pk_official" PRIMARY KEY ("officialID")
);

CREATE TABLE "show_table" (
    "showID"    NUMBER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "branchID"  NUMBER        NOT NULL,
    "town"      VARCHAR2(100) NOT NULL,
    "eventDate" DATE          NOT NULL,
    CONSTRAINT "pk_show" PRIMARY KEY ("showID")
);


-- ------------------------------------------------------------
-- FOREIGN KEYS
-- ------------------------------------------------------------

ALTER TABLE "borrow_table" ADD CONSTRAINT "fk_borrow_member"
    FOREIGN KEY ("memberID") REFERENCES "member_table" ("memberID") ON DELETE CASCADE;

ALTER TABLE "borrow_table" ADD CONSTRAINT "fk_borrow_resource"
    FOREIGN KEY ("resourceID") REFERENCES "resource_table" ("resourceID");

ALTER TABLE "member_table" ADD CONSTRAINT "fk_member_branch"
    FOREIGN KEY ("branchID") REFERENCES "branch_table" ("branchID");

ALTER TABLE "member_table" ADD CONSTRAINT "fk_member_category"
    FOREIGN KEY ("categoryID") REFERENCES "category_table" ("categoryID");

ALTER TABLE "official_table" ADD CONSTRAINT "fk_official_branch"
    FOREIGN KEY ("branchID") REFERENCES "branch_table" ("branchID");

ALTER TABLE "payment_table" ADD CONSTRAINT "fk_payment_member"
    FOREIGN KEY ("memberID") REFERENCES "member_table" ("memberID");

ALTER TABLE "show_table" ADD CONSTRAINT "fk_show_branch"
    FOREIGN KEY ("branchID") REFERENCES "branch_table" ("branchID");


-- ------------------------------------------------------------
-- VIEWS
-- ------------------------------------------------------------

CREATE OR REPLACE VIEW "memberSummary" AS
SELECT m."firstName",
       m."secondName",
       b."branchName",
       c."categoryName"
FROM   "member_table"   m
JOIN   "branch_table"   b ON m."branchID"   = b."branchID"
JOIN   "category_table" c ON m."categoryID" = c."categoryID";

CREATE OR REPLACE VIEW "totalRevenue" AS
SELECT SUM("amount") AS "totalRevenue"
FROM   "payment_table";

CREATE OR REPLACE VIEW "membersPerBranch" AS
SELECT b."branchName",
       COUNT(m."memberID") AS "totalMembers"
FROM   "branch_table" b
LEFT JOIN "member_table" m ON b."branchID" = m."branchID"
GROUP BY b."branchName";

CREATE OR REPLACE VIEW "activeMembers" AS
SELECT m."memberID",
       m."firstName",
       m."secondName",
       COUNT(b."borrowID") AS "totalBorrowed"
FROM   "member_table" m
JOIN   "borrow_table" b ON m."memberID" = b."memberID"
GROUP BY m."memberID", m."firstName", m."secondName";

CREATE OR REPLACE VIEW "resourceUsage" AS
SELECT r."title",
       COUNT(b."borrowID") AS "timesBorrowed"
FROM   "resource_table" r
LEFT JOIN "borrow_table" b ON r."resourceID" = b."resourceID"
GROUP BY r."title";

CREATE OR REPLACE VIEW "revenueByCategory" AS
SELECT c."categoryName",
       SUM(p."amount") AS "totalRevenue"
FROM   "payment_table"  p
JOIN   "member_table"   m ON p."memberID"   = m."memberID"
JOIN   "category_table" c ON m."categoryID" = c."categoryID"
GROUP BY c."categoryName";

-- NOTE: "memberDetails" is expanded by the advanced script (adds joinDate, isActive).
--       getMemberProfile uses SELECT * from this view, so it gains those columns
--       automatically after the advanced script runs.
CREATE OR REPLACE VIEW "memberDetails" AS
SELECT m."memberID",
       m."firstName",
       m."secondName",
       m."email",
       m."phoneNo",
       b."branchName",
       c."categoryName"
FROM   "member_table"   m
JOIN   "branch_table"   b ON m."branchID"   = b."branchID"
JOIN   "category_table" c ON m."categoryID" = c."categoryID";

CREATE OR REPLACE VIEW "membersPerBranchDetailed" AS
SELECT b."branchName",
       m."firstName" || ' ' || m."secondName" AS "memberName"
FROM   "member_table" m
JOIN   "branch_table" b ON m."branchID" = b."branchID";


-- ------------------------------------------------------------
-- PROCEDURES
-- ------------------------------------------------------------

CREATE OR REPLACE PROCEDURE "addMember" (
    p_firstName  IN VARCHAR2,
    p_secondName IN VARCHAR2,
    p_email      IN VARCHAR2,
    p_phoneNo    IN VARCHAR2,
    p_branchID   IN NUMBER,
    p_categoryID IN NUMBER
) AS
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO   v_exists
    FROM   "member_table"
    WHERE  "email" = p_email;

    IF v_exists > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Email already exists: ' || p_email);
    END IF;

    INSERT INTO "member_table" (
        "firstName", "secondName", "email", "phoneNo",
        "branchID", "categoryID", "joinDate"
    ) VALUES (
        p_firstName, p_secondName, p_email, p_phoneNo,
        p_branchID, p_categoryID, SYSDATE
    );
END;
/

CREATE OR REPLACE PROCEDURE "addResource" (
    p_title  IN VARCHAR2,
    p_type   IN VARCHAR2,
    p_copies IN NUMBER
) AS
BEGIN
    INSERT INTO "resource_table" ("title", "type", "availableCopies")
    VALUES (p_title, p_type, p_copies);
END;
/

-- [FIX] Added quotes so this is stored as "borrowResource" (mixed-case) in the
--       data dictionary, consistent with every other procedure and matching the
--       GRANT EXECUTE ON "borrowResource" in the advanced script.
-- [FIX] Added DUP_VAL_ON_INDEX handler for the function-based unique index so
--       duplicate active borrows surface a friendly error instead of ORA-00001.
CREATE OR REPLACE PROCEDURE "borrowResource" (
    p_memberID   IN NUMBER,
    p_resourceID IN NUMBER
) AS
    v_available NUMBER;
BEGIN
    SELECT "availableCopies"
    INTO   v_available
    FROM   "resource_table"
    WHERE  "resourceID" = p_resourceID
    FOR UPDATE;

    IF v_available <= 0 THEN
        RAISE_APPLICATION_ERROR(-20002,
            'No copies available for resourceID: ' || p_resourceID);
    END IF;

    INSERT INTO "borrow_table" ("memberID", "resourceID", "borrowDate")
    VALUES (p_memberID, p_resourceID, SYSDATE);

    UPDATE "resource_table"
    SET    "availableCopies" = "availableCopies" - 1
    WHERE  "resourceID" = p_resourceID;

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20003,
            'Member ' || p_memberID ||
            ' already has an active borrow for resourceID: ' || p_resourceID);
END;
/

CREATE OR REPLACE PROCEDURE "deleteMember" (
    p_memberID IN NUMBER
) AS
BEGIN
    -- WARNING: This hard-deletes the member and cascades to borrow_table.
    -- Any active (unreturned) borrows will be permanently deleted with no archive.
    -- Prefer using toggleMemberActive (added by the advanced script) for soft-delete.
    DELETE FROM "member_table"
    WHERE "memberID" = p_memberID;
END;
/

CREATE OR REPLACE PROCEDURE "getAllBorrowedResources" (
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT br."borrowID",
               m."firstName",
               r."title",
               br."borrowDate"
        FROM   "borrow_table"   br
        JOIN   "member_table"   m ON br."memberID"   = m."memberID"
        JOIN   "resource_table" r ON br."resourceID" = r."resourceID"
        WHERE  br."returnDate" IS NULL;
END;
/

CREATE OR REPLACE PROCEDURE "getBorrowedResources" (
    p_memberID IN NUMBER,
    p_result   OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT r."title" AS "ResourceTitle",
               r."type"  AS "ResourceType"
        FROM   "borrow_table"   b
        JOIN   "resource_table" r ON b."resourceID" = r."resourceID"
        JOIN   "member_table"   m ON b."memberID"   = m."memberID"
        WHERE  m."memberID"    = p_memberID
          AND  b."returnDate" IS NULL;
END;
/

CREATE OR REPLACE PROCEDURE "getBranches" (
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT "branchID", "branchName"
        FROM   "branch_table"
        ORDER BY "branchName";
END;
/

CREATE OR REPLACE PROCEDURE "getCategories" (
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT "categoryID", "categoryName"
        FROM   "category_table"
        ORDER BY "categoryName";
END;
/

CREATE OR REPLACE PROCEDURE "getMemberPayments" (
    p_memberID IN NUMBER,
    p_result   OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT "paymentType", "amount", "paymentDate"
        FROM   "payment_table"
        WHERE  "memberID" = p_memberID
        ORDER BY "paymentDate" DESC;
END;
/

CREATE OR REPLACE PROCEDURE "getMemberProfile" (
    p_memberID IN NUMBER,
    p_result   OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT *
        FROM   "memberDetails"
        WHERE  "memberID" = p_memberID;
END;
/

CREATE OR REPLACE PROCEDURE "getAvailableResources" (
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT "resourceID", "title", "type", "availableCopies"
        FROM   "resource_table"
        WHERE  "availableCopies" > 0
        ORDER BY "title";
END;
/

CREATE OR REPLACE PROCEDURE "getMembers" (
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT "memberID", "firstName", "secondName", "email", "phoneNo"
        FROM   "member_table"
        ORDER BY "secondName", "firstName";
END;
/

-- [FIX] Added quotes so this is stored as "makePayment" (mixed-case), consistent
--       with all other procedures and matching the GRANT in the advanced script.
CREATE OR REPLACE PROCEDURE "makePayment" (
    p_memberID    IN NUMBER,
    p_amount      IN NUMBER,
    p_paymentType IN VARCHAR2
) AS
BEGIN
    INSERT INTO "payment_table" ("memberID", "amount", "paymentType", "paymentDate")
    VALUES (p_memberID, p_amount, p_paymentType, SYSDATE);
    -- No COMMIT — transaction control belongs to the calling application.
END;
/

-- [FIX] Uses an explicit column list to avoid accidentally returning the
--       "pwdHash" invisible column that the advanced script adds to member_table.
CREATE OR REPLACE PROCEDURE "memberLogin" (
    p_email  IN VARCHAR2,
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT "memberID",
               "firstName",
               "secondName",
               "email",
               "phoneNo",
               "branchID",
               "categoryID",
               "joinDate"
        FROM   "member_table"
        WHERE  "email" = p_email;
    -- IMPORTANT: password verification must happen in the application layer
    -- using the hashed value stored in the "pwdHash" column (set via setMemberPassword).
    -- Never return pwdHash to the client.
END;
/

-- [FIX] Added NO_DATA_FOUND handler to surface a friendly error if the
--       borrowID does not exist or has already been returned.
CREATE OR REPLACE PROCEDURE "returnResource" (
    p_borrowID IN NUMBER
) AS
    v_resourceID NUMBER;
BEGIN
    SELECT "resourceID"
    INTO   v_resourceID
    FROM   "borrow_table"
    WHERE  "borrowID"    = p_borrowID
      AND  "returnDate" IS NULL;

    UPDATE "borrow_table"
    SET    "returnDate" = SYSDATE
    WHERE  "borrowID"   = p_borrowID;

    UPDATE "resource_table"
    SET    "availableCopies" = "availableCopies" + 1
    WHERE  "resourceID" = v_resourceID;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20004,
            'BorrowID ' || p_borrowID ||
            ' does not exist or has already been returned.');
END;
/

CREATE OR REPLACE PROCEDURE "updateMember" (
    p_memberID   IN NUMBER,
    p_firstName  IN VARCHAR2,
    p_secondName IN VARCHAR2,
    p_email      IN VARCHAR2,
    p_phoneNo    IN VARCHAR2
) AS
BEGIN
    UPDATE "member_table"
    SET    "firstName"  = p_firstName,
           "secondName" = p_secondName,
           "email"      = p_email,
           "phoneNo"    = p_phoneNo
    WHERE  "memberID"   = p_memberID;
END;
/