-- ============================================================
-- Oracle Migration Script (Corrected)
-- Target: Oracle 12c+
-- Changes from original are marked with -- [FIX] comments
-- ============================================================


-- ------------------------------------------------------------
-- TABLES
-- ------------------------------------------------------------

CREATE TABLE "branch_table" (
    "branchID"   NUMBER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "branchName" VARCHAR2(100) NOT NULL,
    "location"   VARCHAR2(100) NOT NULL,
    CONSTRAINT "pk_branch" PRIMARY KEY ("branchID")
);

CREATE TABLE "category_table" (
    "categoryID"   NUMBER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "categoryName" VARCHAR2(50)  NOT NULL,
    "entryFee"     NUMBER(10, 2),
    "annualFee"    NUMBER(10, 2),
    CONSTRAINT "pk_category"             PRIMARY KEY ("categoryID"),
    CONSTRAINT "uq_category_categoryName" UNIQUE      ("categoryName"),
    CONSTRAINT "ck_category_annualFee"   CHECK        ("annualFee" >= 0),
    CONSTRAINT "ck_category_entryFee"    CHECK        ("entryFee"  >= 0)
);

CREATE TABLE "member_table" (
    "memberID"   NUMBER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "firstName"  VARCHAR2(30)  NOT NULL,
    "secondName" VARCHAR2(30)  NOT NULL,
    "email"      VARCHAR2(100),
    "phoneNo"    VARCHAR2(20),
    "branchID"   NUMBER        NOT NULL,
    "categoryID" NUMBER        NOT NULL,
    -- [FIX] Default joinDate to SYSDATE so it is never NULL on insert
    "joinDate"   DATE          DEFAULT SYSDATE,
    CONSTRAINT "pk_member"        PRIMARY KEY ("memberID"),
    CONSTRAINT "uq_member_phoneNo" UNIQUE      ("phoneNo"),
    CONSTRAINT "uq_member_email"   UNIQUE      ("email")
);

CREATE TABLE "payment_table" (
    "paymentID"   NUMBER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "memberID"    NUMBER        NOT NULL,
    "amount"      NUMBER(10, 2),
    "paymentType" VARCHAR2(30)  NOT NULL,
    -- [FIX] Default paymentDate to SYSDATE so it is never NULL on insert
    "paymentDate" DATE          DEFAULT SYSDATE,
    CONSTRAINT "pk_payment"        PRIMARY KEY ("paymentID"),
    CONSTRAINT "ck_payment_amount" CHECK       ("amount" > 0)
);

-- [FIX] Expanded title from VARCHAR2(50) to VARCHAR2(255) — titles routinely exceed 50 chars
CREATE TABLE "resource_table" (
    "resourceID"      NUMBER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "title"           VARCHAR2(255) NOT NULL,
    "type"            VARCHAR2(50)  NOT NULL,
    "availableCopies" NUMBER        DEFAULT 0 NOT NULL,
    CONSTRAINT "pk_resource"                    PRIMARY KEY ("resourceID"),
    CONSTRAINT "ck_resource_availableCopies"    CHECK       ("availableCopies" >= 0)
);

CREATE TABLE "borrow_table" (
    "borrowID"   NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "memberID"   NUMBER NOT NULL,
    "resourceID" NUMBER NOT NULL,
    -- [FIX] Default borrowDate to SYSDATE so it is never NULL on insert
    "borrowDate"  DATE  DEFAULT SYSDATE,
    "returnDate"  DATE,
    CONSTRAINT "pk_borrow" PRIMARY KEY ("borrowID"),
    -- [FIX] Prevent a member_table from borrowing the same resource_table twice concurrently
    CONSTRAINT "uq_borrow_active" UNIQUE ("memberID", "resourceID", "returnDate")
);

CREATE TABLE "official_table" (
    "officialID" NUMBER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "fullName"   VARCHAR2(60)  NOT NULL,
    "position"   VARCHAR2(50)  NOT NULL,
    "phoneNo"    VARCHAR2(20)  NOT NULL,
    "branchID"   NUMBER        NOT NULL,
    CONSTRAINT "pk_official" PRIMARY KEY ("officialID")
);

-- Note: "show" is a SQL*Plus command; quoting it consistently (as done here) is sufficient for Oracle 12c+
CREATE TABLE "show_table" (
    "showID"    NUMBER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "branchID"  NUMBER        NOT NULL,
    "town"      VARCHAR2(100) NOT NULL,
    "eventDate" DATE          NOT NULL,
    CONSTRAINT "pk_show" PRIMARY KEY ("showID")
);


-- ------------------------------------------------------------
-- FOREIGN KEYS
-- ------------------------------------------------------------

ALTER TABLE "borrow_table" ADD CONSTRAINT "fk_borrow_member"
    FOREIGN KEY ("memberID") REFERENCES "member_table" ("memberID") ON DELETE CASCADE;

ALTER TABLE "borrow_table" ADD CONSTRAINT "fk_borrow_resource"
    FOREIGN KEY ("resourceID") REFERENCES "resource_table" ("resourceID");

ALTER TABLE "member_table" ADD CONSTRAINT "fk_member_branch"
    FOREIGN KEY ("branchID") REFERENCES "branch_table" ("branchID");

ALTER TABLE "member_table" ADD CONSTRAINT "fk_member_category"
    FOREIGN KEY ("categoryID") REFERENCES "category_table" ("categoryID");

ALTER TABLE "official_table" ADD CONSTRAINT "fk_official_branch"
    FOREIGN KEY ("branchID") REFERENCES "branch_table" ("branchID");

ALTER TABLE "payment_table" ADD CONSTRAINT "fk_payment_member"
    FOREIGN KEY ("memberID") REFERENCES "member_table" ("memberID");

ALTER TABLE "show_table" ADD CONSTRAINT "fk_show_branch"
    FOREIGN KEY ("branchID") REFERENCES "branch_table" ("branchID");


-- ------------------------------------------------------------
-- VIEWS
-- ------------------------------------------------------------

CREATE OR REPLACE VIEW "memberSummary" AS
SELECT m."firstName",
       m."secondName",
       b."branchName",
       c."categoryName"
FROM   "member_table"   m
JOIN   "branch_table"   b ON m."branchID"   = b."branchID"
JOIN   "category_table" c ON m."categoryID" = c."categoryID";

CREATE OR REPLACE VIEW "totalRevenue" AS
SELECT SUM("amount") AS "totalRevenue"
FROM   "payment_table";

CREATE OR REPLACE VIEW "membersPerBranch" AS
SELECT b."branchName",
       COUNT(m."memberID") AS "totalMembers"
FROM   "branch_table" b
LEFT JOIN "member_table" m ON b."branchID" = m."branchID"
GROUP BY b."branchName";

-- [FIX] Added memberID and secondName to GROUP BY to avoid merging members with the same first name
CREATE OR REPLACE VIEW "activeMembers" AS
SELECT m."memberID",
       m."firstName",
       m."secondName",
       COUNT(b."borrowID") AS "totalBorrowed"
FROM   "member_table" m
JOIN   "borrow_table" b ON m."memberID" = b."memberID"
GROUP BY m."memberID", m."firstName", m."secondName";

CREATE OR REPLACE VIEW "resourceUsage" AS
SELECT r."title",
       COUNT(b."borrowID") AS "timesBorrowed"
FROM   "resource_table" r
LEFT JOIN "borrow_table" b ON r."resourceID" = b."resourceID"
GROUP BY r."title";

CREATE OR REPLACE VIEW "revenueByCategory" AS
SELECT c."categoryName",
       SUM(p."amount") AS "totalRevenue"
FROM   "payment_table"  p
JOIN   "member_table"   m ON p."memberID"   = m."memberID"
JOIN   "category_table" c ON m."categoryID" = c."categoryID"
GROUP BY c."categoryName";

CREATE OR REPLACE VIEW "memberDetails" AS
SELECT m."memberID",
       m."firstName",
       m."secondName",
       m."email",
       m."phoneNo",
       b."branchName",
       c."categoryName"
FROM   "member_table"   m
JOIN   "branch_table"   b ON m."branchID"   = b."branchID"
JOIN   "category_table" c ON m."categoryID" = c."categoryID";

CREATE OR REPLACE VIEW "membersPerBranchDetailed" AS
SELECT b."branchName",
       m."firstName" || ' ' || m."secondName" AS "memberName"
FROM   "member_table" m
JOIN   "branch_table" b ON m."branchID" = b."branchID";


-- ------------------------------------------------------------
-- PROCEDURES
-- ------------------------------------------------------------

-- [FIX] Raises a proper named exception instead of silently printing and returning.
--       Also explicitly sets joinDate to SYSDATE.
CREATE OR REPLACE PROCEDURE "addMember" (
    p_firstName  IN VARCHAR2,
    p_secondName IN VARCHAR2,
    p_email      IN VARCHAR2,
    p_phoneNo    IN VARCHAR2,
    p_branchID   IN NUMBER,
    p_categoryID IN NUMBER
) AS
    v_exists NUMBER;
    e_email_exists EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_email_exists, -20001);
BEGIN
    SELECT COUNT(*)
    INTO   v_exists
    FROM   "member_table"
    WHERE  "email" = p_email;

    IF v_exists > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Email already exists: ' || p_email);
    END IF;

    INSERT INTO "member_table" (
        "firstName", "secondName", "email", "phoneNo",
        "branchID", "categoryID", "joinDate"
    ) VALUES (
        p_firstName, p_secondName, p_email, p_phoneNo,
        p_branchID, p_categoryID, SYSDATE
    );
END;
/

CREATE OR REPLACE PROCEDURE "addResource" (
    p_title  IN VARCHAR2,
    p_type   IN VARCHAR2,
    p_copies IN NUMBER
) AS
BEGIN
    INSERT INTO "resource_table" ("title", "type", "availableCopies")
    VALUES (p_title, p_type, p_copies);
END;
/

-- [FIX] Added availability check before inserting the borrow_table record,
--       and decrements availableCopies to keep inventory accurate.
CREATE OR REPLACE PROCEDURE borrowResource (
    p_memberID   IN NUMBER,
    p_resourceID IN NUMBER
) AS
    v_available NUMBER;
BEGIN
    SELECT "availableCopies"
    INTO   v_available
    FROM   "resource_table"
    WHERE  "resourceID" = p_resourceID
    FOR UPDATE;                         -- lock the row during the transaction

    IF v_available <= 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No copies available for resourceID: ' || p_resourceID);
    END IF;

    INSERT INTO "borrow_table" ("memberID", "resourceID", "borrowDate")
    VALUES (p_memberID, p_resourceID, SYSDATE);

    UPDATE "resource_table"
    SET    "availableCopies" = "availableCopies" - 1
    WHERE  "resourceID" = p_resourceID;
END;
/

CREATE OR REPLACE PROCEDURE "deleteMember" (
    p_memberID IN NUMBER
) AS
BEGIN
    DELETE FROM "member_table"
    WHERE "memberID" = p_memberID;
END;
/

CREATE OR REPLACE PROCEDURE "getAllBorrowedResources" (
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT br."borrowID",
               m."firstName",
               r."title",
               br."borrowDate"
        FROM   "borrow_table"   br
        JOIN   "member_table"   m  ON br."memberID"   = m."memberID"
        JOIN   "resource_table" r  ON br."resourceID" = r."resourceID"
        WHERE  br."returnDate" IS NULL;
END;
/

CREATE OR REPLACE PROCEDURE "getBorrowedResources" (
    p_memberID IN NUMBER,
    p_result   OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT r."title" AS "ResourceTitle",
               r."type"  AS "ResourceType"
        FROM   "borrow_table"   b
        JOIN   "resource_table" r ON b."resourceID" = r."resourceID"
        JOIN   "member_table"   m ON b."memberID"   = m."memberID"
        WHERE  m."memberID"    = p_memberID
          AND  b."returnDate" IS NULL;
END;
/

-- [FIX] Added ORDER BY for predictable results
CREATE OR REPLACE PROCEDURE "getBranches" (
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT "branchID", "branchName"
        FROM   "branch_table"
        ORDER BY "branchName";
END;
/

-- [FIX] Added ORDER BY for predictable results
CREATE OR REPLACE PROCEDURE "getCategories" (
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT "categoryID", "categoryName"
        FROM   "category_table"
        ORDER BY "categoryName";
END;
/

CREATE OR REPLACE PROCEDURE "getMemberPayments" (
    p_memberID IN NUMBER,
    p_result   OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT "paymentType", "amount", "paymentDate"
        FROM   "payment_table"
        WHERE  "memberID" = p_memberID
        ORDER BY "paymentDate" DESC;
END;
/

CREATE OR REPLACE PROCEDURE "getMemberProfile" (
    p_memberID IN NUMBER,
    p_result   OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT *
        FROM   "memberDetails"
        WHERE  "memberID" = p_memberID;
END;
/

-- [FIX] Renamed from getMemberResources (misleading) to getAvailableResources
--       Added ORDER BY for predictable results
CREATE OR REPLACE PROCEDURE "getAvailableResources" (
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT "resourceID", "title", "type", "availableCopies"
        FROM   "resource_table"
        WHERE  "availableCopies" > 0
        ORDER BY "title";
END;
/

-- [FIX] Added ORDER BY for predictable results
CREATE OR REPLACE PROCEDURE "getMembers" (
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT "memberID", "firstName", "secondName", "email", "phoneNo"
        FROM   "member_table"
        ORDER BY "secondName", "firstName";
END;
/

-- [FIX] Removed COMMIT from inside the procedure.
--       Transaction control (COMMIT/ROLLBACK) belongs to the calling application,
--       not inside stored procedures. An internal COMMIT would silently commit
--       any other open work in the caller's transaction.
CREATE OR REPLACE PROCEDURE makePayment (
    p_memberID    IN NUMBER,
    p_amount      IN NUMBER,
    p_paymentType IN VARCHAR2
) AS
BEGIN
    INSERT INTO "payment_table" ("memberID", "amount", "paymentType", "paymentDate")
    VALUES (p_memberID, p_amount, p_paymentType, SYSDATE);
END;
/

-- [FIX] The original procedure accepted memberID as a login credential alongside email,
--       which is not real authentication (memberID is a sequential integer, not a secret).
--       This procedure has been reworked to simply fetch the member_table record by email so the
--       application layer can handle credential verification properly.
--       IMPORTANT: implement a hashed password column and verify it in the application layer
--       or use a dedicated authentication scheme — do not treat memberID as a password.
CREATE OR REPLACE PROCEDURE "memberLogin" (
    p_email  IN VARCHAR2,
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT *
        FROM   "member_table"
        WHERE  "email" = p_email;
END;
/

-- [FIX] Now also increments availableCopies when a resource_table is returned,
--       keeping inventory counts accurate.
CREATE OR REPLACE PROCEDURE "returnResource" (
    p_borrowID IN NUMBER
) AS
    v_resourceID NUMBER;
BEGIN
    -- Fetch resourceID before updating, to increment copies
    SELECT "resourceID"
    INTO   v_resourceID
    FROM   "borrow_table"
    WHERE  "borrowID"    = p_borrowID
      AND  "returnDate" IS NULL;      -- guard: don't process already-returned borrows

    UPDATE "borrow_table"
    SET    "returnDate" = SYSDATE
    WHERE  "borrowID"   = p_borrowID;

    UPDATE "resource_table"
    SET    "availableCopies" = "availableCopies" + 1
    WHERE  "resourceID" = v_resourceID;
END;
/

CREATE OR REPLACE PROCEDURE "updateMember" (
    p_memberID   IN NUMBER,
    p_firstName  IN VARCHAR2,
    p_secondName IN VARCHAR2,
    p_email      IN VARCHAR2,
    p_phoneNo    IN VARCHAR2
) AS
BEGIN
    UPDATE "member_table"
    SET    "firstName"  = p_firstName,
           "secondName" = p_secondName,
           "email"      = p_email,
           "phoneNo"    = p_phoneNo
    WHERE  "memberID"   = p_memberID;
END;
/
