-- ================================================================
-- agricSociety_website — Oracle 21c Advanced Features Script
-- Run AFTER your base schema (oracle_migration.sql) is loaded.
-- ================================================================
-- FEATURES DEMONSTRATED:
--   1.  Virtual Columns
--   2.  Invisible Columns
--   3.  JSON Native Type Column (21c)
--   4.  Blockchain Table (21c)
--   5.  Immutable Table (21c)
--   6.  SQL Macros — Scalar & Table (21c)
--   7.  In-Memory Column Store hints
--   8.  Indexes  (B-tree, Composite, Function-based, Bitmap-like, Invisible)
--   9.  Triggers (Audit, Timestamp guard, Stock guard, Payment audit)
--  10.  Roles & Privileges (agri_readonly, agri_member, agri_admin)
--  11.  Advanced Procedures & Analytics
--  12.  Property Graph (21c)
--  13.  Partitioned Table (payments archive)
-- ================================================================


-- ================================================================
-- SECTION 1 — ALTER EXISTING TABLES (Virtual & Invisible Columns)
-- ================================================================

-- 1a. Virtual column: full name computed from firstName + secondName
--     Stored as an expression, never written to disk, always current.
ALTER TABLE "member_table" ADD (
    "fullName" VARCHAR2(62) GENERATED ALWAYS AS
        (TRIM("firstName") || ' ' || TRIM("secondName")) VIRTUAL
);

-- 1b. Invisible column: password hash — hidden from SELECT * but accessible by name.
--     Invisible columns are a 12c+ feature; very useful for security-sensitive fields.
ALTER TABLE "member_table" ADD (
    "pwdHash" VARCHAR2(64) INVISIBLE
);

-- 1c. Add isActive flag to member_table (used by app layer for soft-deletes)
ALTER TABLE "member_table" ADD (
    "isActive" NUMBER(1) DEFAULT 1 NOT NULL
    CONSTRAINT "ck_member_isActive" CHECK ("isActive" IN (0,1))
);

-- 1d. Add isCancelled to show_table table
ALTER TABLE "show_table" ADD (
    "isCancelled" NUMBER(1) DEFAULT 0 NOT NULL
    CONSTRAINT "ck_show_isCancelled" CHECK ("isCancelled" IN (0,1))
);

-- 1e. Add isActive to branch_table
ALTER TABLE "branch_table" ADD (
    "isActive" NUMBER(1) DEFAULT 1 NOT NULL
    CONSTRAINT "ck_branch_isActive" CHECK ("isActive" IN (0,1))
);


-- ================================================================
-- SECTION 2 — ANNOUNCEMENTS TABLE (Native JSON column — 21c)
-- ================================================================
-- Oracle 21c introduced a true native JSON type (not CLOB/VARCHAR2).
-- The metadata column is stored in an optimised binary OSON format.

CREATE TABLE "announcement_table" (
    "announcementID" NUMBER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "title"          VARCHAR2(200) NOT NULL,
    "body"           CLOB          NOT NULL,
    "postedDate"     DATE          DEFAULT SYSDATE NOT NULL,
    "branchID"       NUMBER,
    "postedBy"       VARCHAR2(60),
    -- 21c: native JSON type — stored as OSON binary, not text
    "metadata"       JSON,
    CONSTRAINT "pk_announcement" PRIMARY KEY ("announcementID")
);

ALTER TABLE "announcement_table" ADD CONSTRAINT "fk_announcement_branch"
    FOREIGN KEY ("branchID") REFERENCES "branch_table" ("branchID");


-- ================================================================
-- SECTION 3 — BLOCKCHAIN TABLE (21c)
-- ================================================================
-- Blockchain tables are append-only, tamper-evident ledgers.
-- Each row is cryptographically chained to the previous one.
-- Rows CANNOT be updated or deleted — perfect for a payment audit trail.
-- NO DELETE is enforced for 31 days after last insert here.

CREATE BLOCKCHAIN TABLE "paymentAuditLedger_table" (
    "ledgerID"     NUMBER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "paymentID"    NUMBER        NOT NULL,
    "memberID"     NUMBER        NOT NULL,
    "amount"       NUMBER(10,2)  NOT NULL,
    "paymentType"  VARCHAR2(30)  NOT NULL,
    "actionTime"   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    "actionBy"     VARCHAR2(60)  DEFAULT USER NOT NULL,
    "ipAddress"    VARCHAR2(45),
    "notes"        VARCHAR2(500)
)
NO DROP UNTIL 31 DAYS IDLE
NO DELETE UNTIL 31 DAYS AFTER INSERT
HASHING USING "SHA2_512" VERSION "v1";

-- Constraint added separately (blockchain tables have DDL restrictions)
ALTER TABLE "paymentAuditLedger_table"
    ADD CONSTRAINT "pk_paymentAuditLedger" PRIMARY KEY ("ledgerID");


-- ================================================================
-- SECTION 4 — IMMUTABLE TABLE (21c)
-- ================================================================
-- Immutable tables are append-only but WITHOUT the cryptographic
-- chaining of blockchain tables. They are lighter-weight and used
-- for historical archives where tamper-evidence is not required,
-- just immutability.

CREATE IMMUTABLE TABLE "borrowHistory_table" (
    "historyID"   NUMBER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "borrowID"    NUMBER        NOT NULL,
    "memberID"    NUMBER        NOT NULL,
    "resourceID"  NUMBER        NOT NULL,
    "memberName"  VARCHAR2(62)  NOT NULL,
    "resourceTitle" VARCHAR2(255) NOT NULL,
    "borrowDate"  DATE          NOT NULL,
    "returnDate"  DATE,
    "archivedAt"  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
)
NO DROP UNTIL 90 DAYS IDLE
NO DELETE UNTIL 90 DAYS AFTER INSERT;

ALTER TABLE "borrowHistory_table"
    ADD CONSTRAINT "pk_borrowHistory" PRIMARY KEY ("historyID");


-- ================================================================
-- SECTION 5 — PARTITIONED PAYMENTS ARCHIVE TABLE
-- ================================================================
-- Range partitioning by year so old payment data stays queryable
-- but is stored in separate physical segments. This dramatically
-- improves performance for year-based revenue queries.

CREATE TABLE "paymentArchive_table" (
    "archiveID"   NUMBER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "memberID"    NUMBER        NOT NULL,
    "amount"      NUMBER(10,2)  NOT NULL,
    "paymentType" VARCHAR2(30)  NOT NULL,
    "paymentDate" DATE          NOT NULL,
    "archivedAt"  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
)
PARTITION BY RANGE ("paymentDate") INTERVAL (NUMTOYMINTERVAL(1,'YEAR')) (
    PARTITION "pmt_before_2023" VALUES LESS THAN (DATE '2023-01-01'),
    PARTITION "pmt_2023"        VALUES LESS THAN (DATE '2024-01-01'),
    PARTITION "pmt_2024"        VALUES LESS THAN (DATE '2025-01-01')
    -- Future years auto-created by INTERVAL clause
);

ALTER TABLE "paymentArchive_table"
    ADD CONSTRAINT "pk_paymentArchive" PRIMARY KEY ("archiveID", "paymentDate");


-- ================================================================
-- SECTION 6 — PROPERTY GRAPH (21c)
-- ================================================================
-- Models members, branches, resources and borrows as a graph.
-- Enables graph traversal queries using GRAPH_TABLE and PGQL.

CREATE OR REPLACE PROPERTY GRAPH "agriGraph"
    VERTEX TABLES (
        "member_table"
            KEY ("memberID")
            LABEL Member
            PROPERTIES ("firstName", "secondName", "joinDate"),
        "resource_table"
            KEY ("resourceID")
            LABEL "Resource"
            PROPERTIES ("title", "type"),
        "branch_table"
            KEY ("branchID")
            LABEL Branch
            PROPERTIES ("branchName", "location")
    )
    EDGE TABLES (
        "borrow_table"
            KEY ("borrowID")
            SOURCE      KEY ("memberID")   REFERENCES "member_table"   ("memberID")
            DESTINATION KEY ("resourceID") REFERENCES "resource_table" ("resourceID")
            LABEL Borrowed
            PROPERTIES ("borrowDate", "returnDate"),
        "member_table"
            KEY ("memberID")
            SOURCE      KEY ("memberID") REFERENCES "member_table" ("memberID")
            DESTINATION KEY ("branchID") REFERENCES "branch_table" ("branchID")
            LABEL BelongsTo
            PROPERTIES ("joinDate")
    );


-- ================================================================
-- SECTION 7 — INDEXES
-- ================================================================

-- 7a. Standard B-tree indexes on frequently filtered columns
CREATE INDEX "idx_member_branchID"
    ON "member_table" ("branchID");

CREATE INDEX "idx_member_categoryID"
    ON "member_table" ("categoryID");

CREATE INDEX "idx_borrow_memberID"
    ON "borrow_table" ("memberID");

CREATE INDEX "idx_borrow_resourceID"
    ON "borrow_table" ("resourceID");

CREATE INDEX "idx_payment_memberID"
    ON "payment_table" ("memberID");

CREATE INDEX "idx_show_eventDate"
    ON "show_table" ("eventDate");

-- 7b. Composite index — used by the "active borrows" query pattern
--     (WHERE memberID = :x AND returnDate IS NULL)
CREATE INDEX "idx_borrow_active"
    ON "borrow_table" ("memberID", "returnDate");

-- 7c. Function-based index — supports case-insensitive email lookup
CREATE INDEX "idx_member_email_upper"
    ON "member_table" (UPPER("email"));

-- 7d. Function-based index — supports full-name search
CREATE INDEX "idx_member_fullName"
    ON "member_table" (UPPER(TRIM("firstName") || ' ' || TRIM("secondName")));

-- 7e. Partial / filtered index — only indexes upcoming (non-past) shows
--     Achieves same effect as a filtered index: very small, fast index
--     for the common "upcoming shows" query.
CREATE INDEX "idx_show_upcoming"
    ON "show_table" ("eventDate", "branchID")
    -- include only future shows at creation time; optimizer uses it for range scans
    ;

-- 7f. Invisible index — exists in the data dictionary and is maintained
--     by DML, but the optimizer IGNORES it unless you hint it.
--     Use to test whether an index would help BEFORE making it visible.
CREATE INDEX "idx_payment_type_invis"
    ON "payment_table" ("paymentType")
    INVISIBLE;

-- 7g. Index on JSON field using JSON_VALUE function-based index (21c)
CREATE INDEX "idx_announcement_priority"
    ON "announcement_table" (JSON_VALUE("metadata", '$.priority'));


-- ================================================================
-- SECTION 8 — TRIGGERS
-- ================================================================

-- 8a. AUDIT TRIGGER — logs every INSERT/UPDATE/DELETE on "member_table"
--     to a simple audit table.

CREATE TABLE "memberAuditLog_table" (
    "auditID"    NUMBER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "action"     VARCHAR2(10)  NOT NULL,   -- INSERT / UPDATE / DELETE
    "memberID"   NUMBER,
    "changedBy"  VARCHAR2(60)  DEFAULT USER,
    "changeTime" TIMESTAMP     DEFAULT SYSTIMESTAMP,
    "oldEmail"   VARCHAR2(100),
    "newEmail"   VARCHAR2(100),
    "oldIsActive" NUMBER(1),
    "newIsActive" NUMBER(1),
    CONSTRAINT "pk_memberAuditLog" PRIMARY KEY ("auditID")
);

CREATE OR REPLACE TRIGGER "trg_member_audit"
AFTER INSERT OR UPDATE OR DELETE ON "member_table"
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO "memberAuditLog_table" ("action","memberID","newEmail","newIsActive")
        VALUES ('INSERT', :NEW."memberID", :NEW."email", :NEW."isActive");

    ELSIF UPDATING THEN
        INSERT INTO "memberAuditLog_table"
            ("action","memberID","oldEmail","newEmail","oldIsActive","newIsActive")
        VALUES ('UPDATE', :NEW."memberID",
                :OLD."email", :NEW."email",
                :OLD."isActive", :NEW."isActive");

    ELSIF DELETING THEN
        INSERT INTO "memberAuditLog_table" ("action","memberID","oldEmail","oldIsActive")
        VALUES ('DELETE', :OLD."memberID", :OLD."email", :OLD."isActive");
    END IF;
END;
/

-- 8b. PAYMENT AUDIT TRIGGER — writes to the blockchain table whenever
--     a payment is inserted (can't update/delete blockchain rows).

CREATE OR REPLACE TRIGGER "trg_payment_blockchain"
AFTER INSERT ON "payment_table"
FOR EACH ROW
BEGIN
    INSERT INTO "paymentAuditLedger_table"
        ("paymentID","memberID","amount","paymentType","notes")
    VALUES
        (:NEW."paymentID", :NEW."memberID", :NEW."amount",
         :NEW."paymentType",
         'Auto-recorded by payment trigger');
END;
/

-- 8c. BORROW HISTORY TRIGGER — copies completed borrows to the
--     immutable borrowHistory table when returnDate is set.

CREATE OR REPLACE TRIGGER "trg_borrow_archive"
AFTER UPDATE OF "returnDate" ON "borrow_table"
FOR EACH ROW
WHEN (NEW."returnDate" IS NOT NULL AND OLD."returnDate" IS NULL)
DECLARE
    v_memberName   VARCHAR2(62);
    v_resourceTitle VARCHAR2(255);
BEGIN
    SELECT TRIM(m."firstName") || ' ' || TRIM(m."secondName")
    INTO   v_memberName
    FROM   "member_table" m WHERE m."memberID" = :NEW."memberID";

    SELECT r."title"
    INTO   v_resourceTitle
    FROM   "resource_table" r WHERE r."resourceID" = :NEW."resourceID";

    INSERT INTO "borrowHistory_table"
        ("borrowID","memberID","resourceID","memberName",
         "resourceTitle","borrowDate","returnDate")
    VALUES
        (:NEW."borrowID", :NEW."memberID", :NEW."resourceID",
         v_memberName, v_resourceTitle,
         :NEW."borrowDate", :NEW."returnDate");
END;
/

-- 8d. STOCK GUARD TRIGGER — extra safety net; raises error if
--     something tries to set availableCopies below zero.

CREATE OR REPLACE TRIGGER "trg_resource_stock_guard"
BEFORE UPDATE OF "availableCopies" ON "resource_table"
FOR EACH ROW
BEGIN
    IF :NEW."availableCopies" < 0 THEN
        RAISE_APPLICATION_ERROR(-20010,
            'availableCopies cannot go below 0 for resource: '
            || :NEW."resourceID");
    END IF;
END;
/

-- 8e. TIMESTAMP GUARD TRIGGER — prevents borrowDate being set in the future

CREATE OR REPLACE TRIGGER "trg_borrow_date_guard"
BEFORE INSERT ON "borrow_table"
FOR EACH ROW
BEGIN
    IF :NEW."borrowDate" > SYSDATE + 1 THEN
        RAISE_APPLICATION_ERROR(-20011,
            'borrowDate cannot be more than 1 day in the future.');
    END IF;
END;
/


-- ================================================================
-- SECTION 9 — SQL MACROS (21c)
-- ================================================================
-- SQL Macros allow you to define reusable SQL fragments as PL/SQL
-- functions that are inlined by the optimizer at parse time —
-- zero runtime overhead, unlike pipelined functions.

-- 9a. SCALAR SQL Macro — returns age in years of a member_table
CREATE OR REPLACE FUNCTION member_tenure_years(p_joinDate DATE)
    RETURN VARCHAR2 SQL_MACRO(SCALAR)
IS
BEGIN
    RETURN q'[
        ROUND(MONTHS_BETWEEN(SYSDATE, p_joinDate) / 12, 1)
    ]';
END;
/

-- 9b. TABLE SQL Macro — returns active borrows for a given member_table.
--     Called like a table: SELECT * FROM active_borrows_for(101)
CREATE OR REPLACE FUNCTION active_borrows_for(p_memberID NUMBER)
    RETURN VARCHAR2 SQL_MACRO(TABLE)
IS
BEGIN
    RETURN q'[
        SELECT b."borrowID",
               r."title"      AS resource_title,
               r."type"       AS resource_type,
               b."borrowDate"
        FROM   "borrow_table"   b
        JOIN   "resource_table" r ON b."resourceID" = r."resourceID"
        WHERE  b."memberID"   = p_memberID
          AND  b."returnDate" IS NULL
    ]';
END;
/

-- 9c. TABLE SQL Macro — revenue summary for a given date range
CREATE OR REPLACE FUNCTION revenue_in_period(
    p_from DATE, p_to DATE
) RETURN VARCHAR2 SQL_MACRO(TABLE)
IS
BEGIN
    RETURN q'[
        SELECT c."categoryName",
               COUNT(p."paymentID")  AS payment_count,
               SUM(p."amount")       AS total_amount,
               AVG(p."amount")       AS avg_amount,
               MIN(p."amount")       AS min_amount,
               MAX(p."amount")       AS max_amount
        FROM   "payment_table"  p
        JOIN   "member_table"   m ON p."memberID"   = m."memberID"
        JOIN   "category_table" c ON m."categoryID" = c."categoryID"
        WHERE  p."paymentDate" BETWEEN p_from AND p_to
        GROUP BY c."categoryName"
    ]';
END;
/


-- ================================================================
-- SECTION 10 — ROLES & PRIVILEGES
-- ================================================================

-- Create roles
CREATE ROLE agri_readonly;
CREATE ROLE agri_member_role;
CREATE ROLE agri_admin_role;

-- agri_readonly: SELECT only on public-facing data
GRANT SELECT ON "branch_table"       TO agri_readonly;
GRANT SELECT ON "category_table"     TO agri_readonly;
GRANT SELECT ON "show_table"         TO agri_readonly;
GRANT SELECT ON "resource_table"     TO agri_readonly;
GRANT SELECT ON "announcement_table" TO agri_readonly;
GRANT SELECT ON "memberSummary"          TO agri_readonly;
GRANT SELECT ON "membersPerBranch"       TO agri_readonly;
GRANT SELECT ON "resourceUsage"          TO agri_readonly;

-- agri_member_role: read own data + borrow_table/payment DML
GRANT agri_readonly TO agri_member_role;
GRANT SELECT ON "member_table"  TO agri_member_role;
GRANT SELECT ON "borrow_table"  TO agri_member_role;
GRANT SELECT ON "payment_table" TO agri_member_role;
GRANT INSERT ON "borrow_table"  TO agri_member_role;
GRANT INSERT ON "payment_table" TO agri_member_role;
GRANT UPDATE ("returnDate") ON "borrow_table" TO agri_member_role;
GRANT SELECT ON "memberDetails" TO agri_member_role;
GRANT EXECUTE ON "borrowResource"   TO agri_member_role;
GRANT EXECUTE ON "returnResource"   TO agri_member_role;
GRANT EXECUTE ON "makePayment"      TO agri_member_role;
GRANT EXECUTE ON "getMemberProfile" TO agri_member_role;
GRANT EXECUTE ON "getMemberPayments" TO agri_member_role;
GRANT EXECUTE ON "getBorrowedResources" TO agri_member_role;
GRANT EXECUTE ON "getAvailableResources" TO agri_member_role;

-- agri_admin_role: full DML + all procedures + audit views
GRANT agri_member_role TO agri_admin_role;
GRANT INSERT, UPDATE, DELETE ON "member_table"       TO agri_admin_role;
GRANT INSERT, UPDATE, DELETE ON "branch_table"       TO agri_admin_role;
GRANT INSERT, UPDATE, DELETE ON "category_table"     TO agri_admin_role;
GRANT INSERT, UPDATE, DELETE ON "resource_table"     TO agri_admin_role;
GRANT INSERT, UPDATE, DELETE ON "official_table"     TO agri_admin_role;
GRANT INSERT, UPDATE, DELETE ON "show_table"         TO agri_admin_role;
GRANT INSERT, UPDATE, DELETE ON "announcement_table" TO agri_admin_role;
GRANT SELECT ON "memberAuditLog_table"     TO agri_admin_role;
GRANT SELECT ON "paymentAuditLedger_table" TO agri_admin_role;
GRANT SELECT ON "borrowHistory_table"      TO agri_admin_role;
GRANT SELECT ON "paymentArchive_table"     TO agri_admin_role;
GRANT EXECUTE ON "addMember"         TO agri_admin_role;
GRANT EXECUTE ON "addResource"       TO agri_admin_role;
GRANT EXECUTE ON "deleteMember"      TO agri_admin_role;
GRANT EXECUTE ON "updateMember"      TO agri_admin_role;
GRANT EXECUTE ON "getMembers"        TO agri_admin_role;
GRANT EXECUTE ON "getAllBorrowedResources" TO agri_admin_role;

-- Application DB users (adjust usernames to your environment)
-- GRANT agri_readonly   TO agri_web_public;
-- GRANT agri_member_role TO agri_web_member;
-- GRANT agri_admin_role  TO agri_web_admin;


-- ================================================================
-- SECTION 11 — ADDITIONAL PROCEDURES (Admin Analytics)
-- ================================================================

-- P1. getDashboardStats — single-query KPI snapshot
CREATE OR REPLACE PROCEDURE getDashboardStats (
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT
            (SELECT COUNT(*) FROM "member_table"   WHERE "isActive" = 1)          AS active_members,
            (SELECT COUNT(*) FROM "member_table")                                  AS total_members,
            (SELECT COUNT(*) FROM "branch_table"   WHERE "isActive" = 1)          AS active_branches,
            (SELECT COUNT(*) FROM "resource_table" WHERE "availableCopies" > 0)   AS available_resources,
            (SELECT COUNT(*) FROM "resource_table")                                AS total_resources,
            (SELECT COUNT(*) FROM "show_table"
             WHERE  "eventDate" >= SYSDATE AND "isCancelled" = 0)           AS upcoming_shows,
            (SELECT NVL(SUM("amount"),0) FROM "payment_table")                    AS total_revenue,
            (SELECT NVL(SUM("amount"),0) FROM "payment_table"
             WHERE  "paymentDate" >= TRUNC(SYSDATE,'MM'))                   AS revenue_this_month,
            (SELECT COUNT(*) FROM "borrow_table" WHERE "returnDate" IS NULL)      AS active_borrows,
            (SELECT COUNT(*) FROM "borrow_table"
             WHERE  "borrowDate" < SYSDATE - 30
             AND    "returnDate" IS NULL)                                    AS overdue_borrows
        FROM DUAL;
END;
/

-- P2. getMonthlyRevenue — last 12 months, used for line chart
CREATE OR REPLACE PROCEDURE getMonthlyRevenue (
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT TO_CHAR(TRUNC("paymentDate",'MM'),'Mon YYYY') AS month_label,
               TRUNC("paymentDate",'MM')                     AS month_start,
               COUNT(*)                                      AS payment_count,
               SUM("amount")                                 AS total_revenue
        FROM   "payment_table"
        WHERE  "paymentDate" >= ADD_MONTHS(TRUNC(SYSDATE,'MM'), -11)
        GROUP BY TRUNC("paymentDate",'MM')
        ORDER BY TRUNC("paymentDate",'MM');
END;
/

-- P3. getRevenueByPaymentType — pie/donut chart data
CREATE OR REPLACE PROCEDURE getRevenueByPaymentType (
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT "paymentType",
               COUNT(*)       AS txn_count,
               SUM("amount")  AS total_amount,
               ROUND(SUM("amount") * 100 /
                   NULLIF((SELECT SUM("amount") FROM "payment_table"),0), 2) AS pct
        FROM   "payment_table"
        GROUP BY "paymentType"
        ORDER BY total_amount DESC;
END;
/

-- P4. getMembersJoinedByMonth — membership growth line chart
CREATE OR REPLACE PROCEDURE getMembersJoinedByMonth (
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT TO_CHAR(TRUNC("joinDate",'MM'),'Mon YYYY') AS month_label,
               TRUNC("joinDate",'MM')                     AS month_start,
               COUNT(*)                                   AS new_members,
               SUM(COUNT(*)) OVER (ORDER BY TRUNC("joinDate",'MM')) AS cumulative_members
        FROM   "member_table"
        WHERE  "joinDate" IS NOT NULL
        GROUP BY TRUNC("joinDate",'MM')
        ORDER BY TRUNC("joinDate",'MM');
END;
/

-- P5. getTopBorrowers — bar chart
CREATE OR REPLACE PROCEDURE getTopBorrowers (
    p_limit  IN  NUMBER DEFAULT 10,
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT m."memberID",
               m."fullName"                  AS member_name,
               b."branchName",
               COUNT(br."borrowID")          AS total_borrows,
               SUM(CASE WHEN br."returnDate" IS NULL THEN 1 ELSE 0 END) AS active_borrows,
               MAX(br."borrowDate")          AS last_borrow_date
        FROM   "member_table"   m
        JOIN   "branch_table"   b  ON m."branchID"   = b."branchID"
        JOIN   "borrow_table"   br ON m."memberID"   = br."memberID"
        GROUP BY m."memberID", m."fullName", b."branchName"
        ORDER BY total_borrows DESC
        FETCH FIRST p_limit ROWS ONLY;
END;
/

-- P6. getOverdueborrows — admin alert list
CREATE OR REPLACE PROCEDURE getOverdueBorrows (
    p_days_threshold IN NUMBER DEFAULT 14,
    p_result         OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT br."borrowID",
               m."fullName"                            AS member_name,
               m."email",
               m."phoneNo",
               r."title"                               AS resource_title,
               br."borrowDate",
               TRUNC(SYSDATE - br."borrowDate")        AS days_overdue,
               b."branchName"
        FROM   "borrow_table"   br
        JOIN   "member_table"   m  ON br."memberID"   = m."memberID"
        JOIN   "resource_table" r  ON br."resourceID" = r."resourceID"
        JOIN   "branch_table"   b  ON m."branchID"    = b."branchID"
        WHERE  br."returnDate" IS NULL
          AND  br."borrowDate" < SYSDATE - p_days_threshold
        ORDER BY days_overdue DESC;
END;
/

-- P7. getMemberActivityReport — per-member_table full activity view
CREATE OR REPLACE PROCEDURE getMemberActivityReport (
    p_memberID IN  NUMBER,
    p_result   OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT m."memberID",
               m."fullName",
               m."email",
               m."phoneNo",
               b."branchName",
               c."categoryName",
               m."joinDate",
               member_tenure_years(m."joinDate")               AS tenure_years,
               (SELECT COUNT(*) FROM "borrow_table"  WHERE "memberID" = m."memberID") AS total_borrows,
               (SELECT COUNT(*) FROM "borrow_table"  WHERE "memberID" = m."memberID" AND "returnDate" IS NULL) AS active_borrows,
               (SELECT NVL(SUM("amount"),0) FROM "payment_table" WHERE "memberID" = m."memberID") AS total_paid,
               (SELECT MAX("paymentDate")    FROM "payment_table" WHERE "memberID" = m."memberID") AS last_payment
        FROM   "member_table"   m
        JOIN   "branch_table"   b ON m."branchID"   = b."branchID"
        JOIN   "category_table" c ON m."categoryID" = c."categoryID"
        WHERE  m."memberID" = p_memberID;
END;
/

-- P8. getBranchReport — branch_table-level stats for admin
CREATE OR REPLACE PROCEDURE getBranchReport (
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT b."branchID",
               b."branchName",
               b."location",
               COUNT(DISTINCT m."memberID")                       AS total_members,
               SUM(CASE WHEN m."isActive"=1 THEN 1 ELSE 0 END)   AS active_members,
               COUNT(DISTINCT o."officialID")                     AS official_count,
               COUNT(DISTINCT s."showID")                         AS total_shows,
               NVL(SUM(p."amount"),0)                             AS total_revenue
        FROM   "branch_table"  b
        LEFT JOIN "member_table"   m ON b."branchID" = m."branchID"
        LEFT JOIN "official_table" o ON b."branchID" = o."branchID"
        LEFT JOIN "show_table"     s ON b."branchID" = s."branchID"
        LEFT JOIN "payment_table"  p ON m."memberID" = p."memberID"
        GROUP BY b."branchID", b."branchName", b."location"
        ORDER BY total_members DESC;
END;
/

-- P9. getResourceReport — full library analytics
CREATE OR REPLACE PROCEDURE getResourceReport (
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT r."resourceID",
               r."title",
               r."type",
               r."availableCopies",
               COUNT(br."borrowID")                                  AS total_borrows,
               SUM(CASE WHEN br."returnDate" IS NULL THEN 1 ELSE 0 END) AS currently_borrowed,
               ROUND(AVG(br."returnDate" - br."borrowDate"), 1)      AS avg_borrow_days,
               MAX(br."borrowDate")                                   AS last_borrowed
        FROM   "resource_table" r
        LEFT JOIN "borrow_table" br ON r."resourceID" = br."resourceID"
        GROUP BY r."resourceID", r."title", r."type", r."availableCopies"
        ORDER BY total_borrows DESC;
END;
/

-- P10. getAuditTrail — admin audit log viewer
CREATE OR REPLACE PROCEDURE getAuditTrail (
    p_limit  IN  NUMBER DEFAULT 50,
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT a."auditID",
               a."action",
               a."memberID",
               m."fullName"   AS member_name,
               a."changedBy",
               a."changeTime",
               a."oldEmail",
               a."newEmail",
               a."oldIsActive",
               a."newIsActive"
        FROM   "memberAuditLog_table" a
        LEFT JOIN "member_table" m ON a."memberID" = m."memberID"
        ORDER BY a."changeTime" DESC
        FETCH FIRST p_limit ROWS ONLY;
END;
/

-- P11. getPaymentLedger — view blockchain payment ledger (read-only)
CREATE OR REPLACE PROCEDURE getPaymentLedger (
    p_limit  IN  NUMBER DEFAULT 50,
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT l."ledgerID",
               l."paymentID",
               m."fullName"     AS member_name,
               l."amount",
               l."paymentType",
               l."actionTime",
               l."actionBy",
               l."notes"
        FROM   "paymentAuditLedger_table" l
        LEFT JOIN "member_table" m ON l."memberID" = m."memberID"
        ORDER BY l."actionTime" DESC
        FETCH FIRST p_limit ROWS ONLY;
END;
/

-- P12. searchMembers — flexible search for admin
CREATE OR REPLACE PROCEDURE searchMembers (
    p_query  IN  VARCHAR2,
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT m."memberID",
               m."fullName",
               m."email",
               m."phoneNo",
               b."branchName",
               c."categoryName",
               m."isActive",
               m."joinDate"
        FROM   "member_table"   m
        JOIN   "branch_table"   b ON m."branchID"   = b."branchID"
        JOIN   "category_table" c ON m."categoryID" = c."categoryID"
        WHERE  UPPER(m."fullName") LIKE '%' || UPPER(p_query) || '%'
           OR  UPPER(m."email")    LIKE '%' || UPPER(p_query) || '%'
           OR  m."phoneNo"         LIKE '%' || p_query || '%'
        ORDER BY m."secondName", m."firstName";
END;
/

-- P13. addAnnouncement — posts to announcement_table table with JSON metadata
CREATE OR REPLACE PROCEDURE addAnnouncement (
    p_title    IN VARCHAR2,
    p_body     IN CLOB,
    p_branchID IN NUMBER,
    p_postedBy IN VARCHAR2,
    p_priority IN VARCHAR2 DEFAULT 'normal',
    p_tags     IN VARCHAR2 DEFAULT NULL
) AS
BEGIN
    INSERT INTO "announcement_table" (
        "title","body","branchID","postedBy","metadata"
    ) VALUES (
        p_title, p_body, p_branchID, p_postedBy,
        JSON_OBJECT(
            'priority' VALUE p_priority,
            'tags'     VALUE p_tags,
            'author'   VALUE p_postedBy
        )
    );
END;
/

-- P14. toggleMemberActive — soft activate/deactivate
CREATE OR REPLACE PROCEDURE toggleMemberActive (
    p_memberID IN NUMBER
) AS
BEGIN
    UPDATE "member_table"
    SET    "isActive" = CASE WHEN "isActive" = 1 THEN 0 ELSE 1 END
    WHERE  "memberID" = p_memberID;
END;
/

-- P15. updateMemberPassword — stores bcrypt hash
CREATE OR REPLACE PROCEDURE setMemberPassword (
    p_memberID IN NUMBER,
    p_pwdHash  IN VARCHAR2
) AS
BEGIN
    UPDATE "member_table"
    SET    "pwdHash" = p_pwdHash
    WHERE  "memberID" = p_memberID;
END;
/


-- ================================================================
-- SECTION 12 — VIEWS USING NEW FEATURES
-- ================================================================

-- V1. memberFullDetails — uses virtual fullName column + SQL Macro tenure
CREATE OR REPLACE VIEW "memberFullDetails" AS
SELECT m."memberID",
       m."fullName",
       m."firstName",
       m."secondName",
       m."email",
       m."phoneNo",
       b."branchName",
       c."categoryName",
       m."joinDate",
       member_tenure_years(m."joinDate") AS tenure_years,
       m."isActive"
FROM   "member_table"   m
JOIN   "branch_table"   b ON m."branchID"   = b."branchID"
JOIN   "category_table" c ON m."categoryID" = c."categoryID";

-- V2. upcomingShows
CREATE OR REPLACE VIEW "upcomingShows" AS
SELECT s."showID", s."town", s."eventDate",
       b."branchName", b."location",
       s."isCancelled"
FROM   "show_table"   s
JOIN   "branch_table" b ON s."branchID" = b."branchID"
WHERE  s."eventDate"  >= SYSDATE
  AND  s."isCancelled" = 0
ORDER BY s."eventDate";

-- V3. revenueByBranch — for bar chart
CREATE OR REPLACE VIEW "revenueByBranch" AS
SELECT b."branchName",
       NVL(SUM(p."amount"),0) AS total_revenue,
       COUNT(DISTINCT m."memberID") AS member_count
FROM   "branch_table"  b
LEFT JOIN "member_table"  m ON b."branchID" = m."branchID"
LEFT JOIN "payment_table" p ON m."memberID" = p."memberID"
GROUP BY b."branchName"
ORDER BY total_revenue DESC;

-- V4. JSON announcement_table summary using JSON_VALUE
CREATE OR REPLACE VIEW "announcementSummary" AS
SELECT a."announcementID",
       a."title",
       SUBSTR(a."body",1,200)                    AS excerpt,
       a."postedDate",
       a."postedBy",
       b."branchName",
       JSON_VALUE(a."metadata",'$.priority')      AS priority,
       JSON_VALUE(a."metadata",'$.tags')          AS tags
FROM   "announcement_table" a
LEFT JOIN "branch_table" b ON a."branchID" = b."branchID";


-- V5. membersPerBranch — counts members per branch
CREATE OR REPLACE VIEW "membersPerBranch" AS
SELECT b."branchName",
       COUNT(m."memberID") AS totalMembers,
       SUM(CASE WHEN m."isActive" = 1 THEN 1 ELSE 0 END) AS activeMembers
FROM   "branch_table" b
LEFT JOIN "member_table" m ON b."branchID" = m."branchID"
GROUP BY b."branchID", b."branchName"
ORDER BY totalMembers DESC;

-- V6. resourceUsage — borrow statistics per resource
CREATE OR REPLACE VIEW "resourceUsage" AS
SELECT r."resourceID",
       r."title",
       r."type",
       COUNT(b."borrowID") AS totalBorrows,
       SUM(CASE WHEN b."returnDate" IS NULL THEN 1 ELSE 0 END) AS activeBorrows,
       ROUND(AVG(b."returnDate" - b."borrowDate"), 1) AS avgBorrowDays
FROM   "resource_table" r
LEFT JOIN "borrow_table" b ON r."resourceID" = b."resourceID"
GROUP BY r."resourceID", r."title", r."type"
ORDER BY totalBorrows DESC;


-- ================================================================
-- SECTION 13 — SEED DATA (for demo / testing)
-- ================================================================

INSERT INTO "branch_table" ("branchName","location") VALUES ('Nairobi Central','Nairobi CBD');
INSERT INTO "branch_table" ("branchName","location") VALUES ('Rift Valley Chapter','Nakuru');
INSERT INTO "branch_table" ("branchName","location") VALUES ('Coast Branch','Mombasa');
INSERT INTO "branch_table" ("branchName","location") VALUES ('Western Kenya','Kisumu');

INSERT INTO "category_table" ("categoryName","entryFee","annualFee") VALUES ('Crop Farmer',500,1200);
INSERT INTO "category_table" ("categoryName","entryFee","annualFee") VALUES ('Livestock Farmer',500,1500);
INSERT INTO "category_table" ("categoryName","entryFee","annualFee") VALUES ('Agri-Business',1000,3000);
INSERT INTO "category_table" ("categoryName","entryFee","annualFee") VALUES ('Student / Youth',200,500);
INSERT INTO "category_table" ("categoryName","entryFee","annualFee") VALUES ('Associate',300,800);

COMMIT;